name: Docker Dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'DEV-VERSION'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load VERSION
        run: echo "VERSION=$(cat DEV-VERSION)" >> $GITHUB_ENV  

      - name: Wait For Complie
        run: sleep 180s

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建镜像
        uses: docker/build-push-action@v5
        with:
          file: ./DEV-Dockerfile
          platforms: linux/amd64
          push: true
          tags: | 
            wjqserver/ghproxy-0rtt:${{ env.VERSION }}
            wjqserver/ghproxy-0rtt:dev
